name: mosaic-register-lambda-deploy

on:
  push:
    branches:
      - master
    paths:
      - "mosaic-register-lambda/**"
jobs:
  lambda-cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - run: cd mosaic-register-lambda && pip install -r requirements.txt . && zip -r package.zip ./*
      - run: pip3 install awscli
      - run: cd mosaic-register-lambda && aws lambda update-function-code --function-name mosaic-dev-register-lambda --zip-file fileb://package.zip --publish
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-central-1
