name: mosaic-dev-resultimg-lambda-deploy

on:
  push:
    branches:
      - master
    paths:
      - "mosaic-resultimage-lambda/**"

env:
  DOCKER_BUILDKIT: "1"
  AWS_ACCOUNT_ID: "597775291172"
  AWS_DEFAULT_REGION: "eu-central-1"
  FUNCTION_NAME: "mosaic-dev-resultimg-function"
  REPO_NAME: "mosaic-resultimg-function-ecr-repo"
  ENV: "dev"

jobs:
  lambda-cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - run: aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-central-1
      - run: cd mosaic-delete-sabject-list-lambda docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$REPO_NAME:${{ github.sha }}
      - run: docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$REPO_NAME:${{ github.sha }}
      - run: pip3 install awscli
      - run: aws lambda update-function-code --region $AWS_DEFAULT_REGION --function-name $FUNCTION_NAME --image-uri $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$REPO_NAME:${{ github.sha }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-central-1
